# Base dev image
FROM ubuntu:24.04

# Install dev dependencies
RUN apt-get update && \
    apt-get install -y build-essential cmake g++ make git clang-format clang-tidy cppcheck lldb sudo python3 python3-pip ninja-build && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

# Default entrypoint: launch dev menu
CMD ["./scripts/dev_menu.sh"]
