# Base image
FROM ubuntu:24.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    make \
    clang-format \
    clang-tidy \
    cppcheck \
    git \
    python3 \
    python3-pip \
    && apt-get clean

# Set workdir
WORKDIR /app

# Copy project files
COPY . .

# Default command: build and run pre-commit
CMD ["bash"]
