# Base prod image
FROM ubuntu:24.04

# Only runtime dependencies
RUN apt-get update && \
    apt-get install -y libstdc++6 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=redix-dev:latest /app/build/Release ./build/Release

# Default entrypoint: run RediX binary
CMD ["./build/Release/RediX"]
